version: "3.5"

services:
    api01: &api
        container_name: api01
        build:
            context: .
        depends_on:
            - mysql

    api02:
        <<: *api
        container_name: api02

    horizon:
        <<: *api
        container_name: horizon
        command: ["php", "artisan", "horizon"]

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"

    mysql:
        image: mysql:8
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rinha
            MYSQL_USER: diego
            MYSQL_PASSWORD: 123456
        ports:
            - "3306:3306"
        volumes:
            - mysql-vol:/var/lib/mysql

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"

volumes:
    mysql-vol:
